export const REQUEST = Symbol('等待')
export const LOGIN_SUCCESS = Symbol('登录成功')
export const LOGIN_FAILURE = Symbol('登录失败')
export const LOGOUT_SUCCESS = Symbol('登出成功')
export const LOGIN_SAGA = Symbol('异步登录')
